# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userChecked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkedItem', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userItem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopItem', to='login.User')),
            ],
        ),
    ]
