# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='userChecked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkedItems', to='login.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='userItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userItems', to='login.User'),
        ),
    ]
