# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentPost',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='postComments', to='sync.Post'),
        ),
    ]
