# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_comment_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postRecipe',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reicpePosts', to='sync.Recipe'),
            preserve_default=False,
        ),
    ]
