# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_post_postrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postRecipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reicpePosts', to='sync.Recipe'),
        ),
    ]
